# Login
GO_TO_LOGIN_BUTTON = "button.btn-standard.call-to-action"
EMAIL_FIELD = "#email"
PASSWORD_FIELD = "#password"
CONFIRM_CREDENTIALS_BUTTON = "#btnLogin"
WRONG_CREDENTIALS_NOTIFICATION = "#loginForm > div.general-error > div > div"
REQUEST_VERIFICATION_CODE_BUTTON = ""

# Verify device
VERIFICATION_CODE_FIELD = ""
CONFIRM_VERIFICATION_CODE_BUTTON = ""
WRONG_VERIFICATION_CODE = ""

# Sidebar
GO_TO_TRANSFERS_BUTTON = ""

# Refresh transfer list
GO_TO_TRANSFER_LIST_BUTTON = ""
REMOVE_SOLD_ITEMS_BUTTON = ""
RELIST_UNSOLD_ITEMS_BUTTON = ""
CONFIRM_RELIST_BUTTON = ""

# Set bid filter
GO_TO_SEARCH_THE_TRANSFER_MARKET_BUTTON = ""
NAME_FIELD = ""
NAME_BUTTON = ""
MAX_BID_PRICE_FIELD = ""

# Bid on items
SEARCH_THE_TRANSFER_MARKET_BUTTON = ""
SEARCH_RESULTS = ""
BID_PRICE_FIELD = ""
BID_BUTTON = ""
TIME_LEFT_LABEL = ""

# List won items
GO_TO_TRANSFER_TARGETS_BUTTON = ""
CLEAR_EXPIRED_PLAYERS_BUTTON = ""
WON_ITEMS = ""
WON_ITEM_NAME = ""
OPEN_LIST_DIALOG_BUTTON = ""
START_PRICE_FIELD = ""
MAX_BUY_NOW_FIELD = ""
CONFIRM_LISTING_BUTTON = ""
