# Login
GO_TO_LOGIN_BUTTON = 'button.btn-standard.call-to-action'
EMAIL_FIELD = '#email'
PASSWORD_FIELD = '#password'
CONFIRM_CREDENTIALS_BUTTON = '#btnLogin'
WRONG_CREDENTIALS_NOTIFICATION = '#loginForm > div.general-error > div > div'

# Verify device
REQUEST_VERIFICATION_CODE_BUTTON = ''
CONFIRM_VERIFICATION_CODE_BUTTON = ''
WRONG_VERIFICATION_CODE = ''

# Set bid filter
GO_TO_TRANSFERS_BUTTON = ''
GO_TO_SEARCH_THE_TRANSFER_MARKET_BUTTON = ''
NAME_FIELD = ''
NAME_BUTTON = ''
MAX_BID_PRICE_FIELD = ''
