# Login
GO_TO_LOGIN_BUTTON = "button.btn-standard.call-to-action"
EMAIL_FIELD = "#email"
PASSWORD_FIELD = "#password"
CONFIRM_CREDENTIALS_BUTTON = "#btnLogin"
WRONG_CREDENTIALS_NOTIFICATION = "#loginForm > div.general-error > div > div"

# Verify device
REQUEST_VERIFICATION_CODE_BUTTON = ""
CONFIRM_VERIFICATION_CODE_BUTTON = ""
WRONG_VERIFICATION_CODE = ""

# Refresh transfer list
GO_TO_TRANSFER_LIST_BUTTON = ""
REMOVE_SOLD_ITEMS_BUTTON = ""
RELIST_UNSOLD_ITEMS_BUTTON = ""
CONFIRM_RELIST_BUTTON = ""

# Set bid filter
GO_TO_TRANSFERS_BUTTON = ""
GO_TO_SEARCH_THE_TRANSFER_MARKET_BUTTON = ""
NAME_FIELD = ""
NAME_BUTTON = ""
MAX_BID_PRICE_FIELD = ""

# Bid on items
SEARCH_THE_TRANSFER_MARKET_BUTTON = ""
SEARCH_RESULTS = ""
